Revert "WPEFramework dependency (namespace) is coming from the PackageConfig file"
This reverts commit ce116327117b38833a8531e6c49f4e1050f499c4 as it caused the following compilation errors:

/home/dwrobel/projects/webkit/WebPlatformForEmbedded-2.22/3/OCDM-Playready/MediaSystem.cpp:26:10: fatal error: core/core.h: No such file or directory
 #include <core/core.h>
          ^~~~~~~~~~~~~